version: '2'
services:
  web:
    # image: joshhsoj1902/docker-ogpweb:latest
    image: joshhsoj1902/docker-kong-ogpweb:latest
    restart: always
    environment:
      - OGP_INSTALL=true
      - MYSQL_IP=my_db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=opengamepanel
      - MYSQL_USER=ogpuser
      - MYSQL_PASS=foo
      - MYSQL_PREFIX=ogp_
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=adminadmin
      - ADMIN_EMAIL=admin@email.com
    ports:
      - "10001:80"
    links:
      - db:my_db
    depends_on:
      - db
  db:
    restart: always
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=opengamepanel
      - MYSQL_USER=ogpuser
      - MYSQL_PASSWORD=foo
    volumes:
      - /var/lib/mysql
  agent:
    restart: always
    image: joshhsoj1902/docker-gogpagent:latest
    ports:
     - "12679:12679"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/root/gcloud:/run/secrets/gcloud
    environment:
      - OGP_LISTEN_PORT=12679
      - OGP_KEY=encryption_key2
      - OGP_DOCKER_NAMESPACE=joshhsoj1902
      - OGP_GCLOUD_JSON=/run/secrets/gcloud
      - STORAGE=LOCAL
      # - STORAGE=nfs
      # - STORAGE_NFS_ADDRESS=fileserver
      # - STORAGE_NFS_PATH=/mnt/fileserver/path/
      # - PLACEMENT_CONSTRAINT_1=node.role == manager
      # - PLACEMENT_CONSTRAINT_2=node.labels.foo == true
      # - PLACEMENT_CONSTRAINT_3=baz