defaults: &defaults 
    working_directory: ~/build
    docker: 
      - image: joshhsoj1902/circleci-build-image:1.0.8@sha256:87c9fcce5f5474f34407f12640fd89903070e4de467724294e687a4442d2fe0c
version: 2.1

orbs:
    docker: joshhsoj1902/docker@0.19.0

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: setup workspace
          background: true
          command: |
            cp -rp docker-compose.yml Makefile scripts /tmp/workspace
            ls -ltr /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths: 
            - docker-compose.yml
            - Makefile
            - scripts

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - docker/build:
          context: org-global
          image: joshhsoj1902/docker-gogpagent
          tag: latest
          requires: 
            - setup
      - docker/container-health:
          name: compose-test-web
          composeFile: docker-compose.yml
          service: web
          requires:
            - docker/build
 

